In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [3]:
df= pd.read_table(filepath_or_buffer=r"C:\Users\adity\SMSSpamCollection",names=["label","message"])

In [5]:
df

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [7]:
###shape of the data

In [9]:
df.shape

(5572, 2)

In [11]:
df.label.value_counts()

label
ham     4825
spam     747
Name: count, dtype: int64

In [13]:
df["label"] = df["label"].map({"ham":0,"spam":1})

In [15]:
df

label                                            message
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...
3         0  U dun say so early hor... U c already then say...
4         0  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5567      1  This is the 2nd time we have tried 2 contact u...
5568      0               Will ü b going to esplanade fr home?
5569      0  Pity, * was in mood for that. So...any other s...
5570      0  The guy did some bitching but I acted like i'd...
5571      0                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [17]:
from sklearn.feature_extraction.text import CountVectorizer

In [19]:
count_vector = CountVectorizer()

In [21]:
x=df["message"]
y=df.label

In [23]:
x.head()

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: message, Length: 5572, dtype: object

In [27]:
y.head()

0    0
1    0
2    1
3    0
4    0
Name: label, dtype: int64

In [29]:
from sklearn.model_selection import train_test_split

In [31]:
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [35]:
print("size of the actual dataset: ",df.shape[0])
print("size of the training dataset: ",X_train.shape[0])
print("size of the test dataset: ",X_test.shape[0])

size of the actual dataset:  5572
size of the training dataset:  4457
size of the test dataset:  1115


In [51]:
x_count_train = count_vector.fit_transform(X_train)
x_count_test = count_vector.transform(X_test)

In [53]:
from sklearn.naive_bayes import MultinomialNB

In [55]:
mb = MultinomialNB()

In [57]:
mb.fit(x_count_train,y_train)
mb.score(x_count_train,y_train)

0.9932690150325331

In [63]:
y_pred=mb.predict(x_count_test)

In [65]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [67]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('Accuracy score: ', format(accuracy_score(y_test, y_pred)))
print('Precision score: ', format(precision_score(y_test, y_pred)))
print('Recall score: ', format(recall_score(y_test, y_pred)))
print('F1 score: ', format(f1_score(y_test, y_pred)))

Accuracy score:  0.9919282511210762
Precision score:  1.0
Recall score:  0.9395973154362416
F1 score:  0.9688581314878892


In [107]:
spam_word_prob = mb.feature_log_prob_[1]

In [119]:
spam_word_prob[0:30]

array([-7.78715148, -6.80632223, -9.98437606, -8.88576377, -9.29122888,
       -9.29122888, -9.29122888, -9.29122888, -8.03846591, -8.5980817 ,
       -9.29122888, -8.88576377, -9.29122888, -9.29122888, -7.68179096,
       -7.58648078, -9.29122888, -8.5980817 , -8.88576377, -8.88576377,
       -8.03846591, -8.88576377, -9.29122888, -9.29122888, -9.29122888,
       -9.29122888, -8.88576377, -9.29122888, -9.29122888, -8.88576377])

In [113]:
words = count_vector.get_feature_names_out()

In [117]:
words[0:30]

array(['00', '000', '000pes', '008704050406', '0089', '0121',
       '01223585236', '01223585334', '02', '0207', '02072069400',
       '02073162414', '02085076972', '021', '03', '04', '0430', '05',
       '050703', '0578', '06', '07', '07008009200', '07046744435',
       '07090298926', '07099833605', '07123456789', '0721072',
       '07732584351', '07734396839'], dtype=object)

In [137]:
spam_words = sorted(zip(spam_word_prob, words), reverse=True)
print("Top spam words:")
for prob, word in spam_words[:500]:  # Top 10 words
    print(f"{word}: {np.exp(prob):.4f}")

Top spam words:
to: 0.0255
call: 0.0131
you: 0.0106
your: 0.0099
free: 0.0087
now: 0.0077
for: 0.0075
the: 0.0074
or: 0.0074
txt: 0.0058
on: 0.0055
is: 0.0054
ur: 0.0051
from: 0.0048
text: 0.0047
mobile: 0.0047
stop: 0.0047
have: 0.0045
and: 0.0045
reply: 0.0042
claim: 0.0041
with: 0.0040
www: 0.0037
of: 0.0036
this: 0.0032
get: 0.0032
in: 0.0030
are: 0.0030
prize: 0.0030
our: 0.0030
only: 0.0030
send: 0.0030
cash: 0.0030
new: 0.0028
just: 0.0027
uk: 0.0027
no: 0.0027
win: 0.0026
won: 0.0025
150p: 0.0025
nokia: 0.0024
50: 0.0024
week: 0.0023
urgent: 0.0023
tone: 0.0022
out: 0.0021
be: 0.0021
please: 0.0021
msg: 0.0021
com: 0.0021
service: 0.0020
co: 0.0020
we: 0.0019
contact: 0.0019
16: 0.0019
guaranteed: 0.0019
18: 0.0019
phone: 0.0018
customer: 0.0018
will: 0.0018
per: 0.0018
min: 0.0018
500: 0.0017
who: 0.0017
cs: 0.0017
been: 0.0017
100: 0.0016
1000: 0.0016
chat: 0.0015
awarded: 0.0015
draw: 0.0015
sms: 0.0014
camera: 0.0014
by: 0.0014
wk: 0.0014
if: 0.0014
ringtone: 0.0013
mins: 0

In [155]:
# Input spam message
test_message = "Congratulations! You have won a FREE prize! Reply NOW to claim your cash reward or text 'WIN' to our service number. Hurry, this is urgent!"

# Preprocess the message using the CountVectorizer
test_vector = count_vector.transform([test_message])

# Predict using the Naive Bayes model
prediction = mb.predict(test_vector) # Outputs class (0 for ham, 1 for spam)
print(prediction)

# Get the probability of the prediction
prediction_prob = mb.predict_proba(test_vector) # Outputs probabilities for each class
print(prediction_prob)

# Display the results
if prediction[0] == 1:
    print("The message is SPAM.")
else:
    print("The message is HAM.")

print(f"Probability of Spam: {prediction_prob[0][1]:.4f}")
print(f"Probability of Ham: {prediction_prob[0][0]:.4f}")


[1]
[[1.16905169e-16 1.00000000e+00]]
The message is SPAM.
Probability of Spam: 1.0000
Probability of Ham: 0.0000


In [157]:
message2 = "Congratulations! You’ve won a FREE holiday! Reply ‘WIN’ now to claim your prize or call 123456789. Hurry, offer valid for today only!"

In [159]:
message_count2 = count_vector.transform([message2])

In [161]:
prediction2 = mb.predict(message_count2)

In [163]:
prediction2

array([1], dtype=int64)